default_language_version:
  python: python3.10
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: isort
        types: [ python ]
      - id: black
        name: black
        language: system
        types_or: [ python, pyi ]
        entry: black
      - id: autoflake
        name: autoflake
        language: system
        types_or: [ python, pyi ]
        entry: >
          autoflake --in-place
          --remove-all-unused-imports
          --remove-duplicate-keys
          --remove-unused-variables
          --ignore-init-module-imports
      - id: flake8
        name: flake8
        language: system
        entry: flake8-cached . --config .flake8
        types_or: [ python ]
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        types_or: [ python ]